development:
  adapter: postgresql
  database: ptls
  username: rdaigle
  password: 

test:
  adapter: postgresql
  database: ptls-test
  username: rdaigle
  password: 

  # Schema search path.  The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Character set encoding.  The server defaults to sql_ascii.
  #encoding: UTF8

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   info, notice, warning, error, log, fatal, or panic
  # The server defaults to notice.
  #min_messages: warning